// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OC.DiscordBotServer;

namespace OC.DiscordBotServer.Migrations
{
    [DbContext(typeof(BotDataContext))]
    partial class BotDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("OC.DiscordBotServer.Models.Chanel2Server", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IP")
                        .IsRequired();

                    b.Property<DateTime>("LastOnlineTime");

                    b.Property<DateTime>("LastCheckTime");

                    b.Property<ulong>("LinkCreator");

                    b.Property<int>("Port");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.ToTable("Chanel2Servers");
                });

            modelBuilder.Entity("OC.DiscordBotServer.Models.OCUser", b =>
                {
                    b.Property<ulong>("DiscordIdChanel");

                    b.Property<ulong>("UserId");

                    b.Property<DateTime>("LastActiveTime");

                    b.Property<string>("OCLogin");

                    b.HasKey("DiscordIdChanel", "UserId");

                    b.ToTable("OCUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
